name: Gradle Wrapper Update
on:
  schedule:
    - cron : "0 0 * * *" # Check updates each day on 12AM UTC

jobs:
  gradle_update:
    name: Gradle Update Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: develop
      - name: Gradle Wrapper Check
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          reviewers: PhilippHeuer, iProdigy
          labels: dependencies
          base-branch: deps/gradle-updates
          target-branch: develop
